### PR TITLE
Adding Obq_Color and Obq_ColorspaceConverter for Arnold5

### PR DESCRIPTION
**Pull request by Xelt**
Hi Marc, could you compile this change on your side and see if I did it right?

### CODE REVIEW

**Comment by madesjardins** [comment]
Thanks Patrick, truly appreciated.

**Comment by madesjardins** [comment]
Builds like a charm :) Merci.

**Comment by Xelt** [comment]
Good. If you could compile linux too it would be great.

**Comment by madesjardins** [comment]
Done and pushed :)

**Comment by Xelt** [comment]
Merci!

**Pull request merged**
