### PR TITLE
Update Mac OS X to Arnold 4.2.13.3, LDPK to v1.8.1, Refactor Obq_UVRemapLensDistortion

### PR DESCRIPTION
**Pull request by up4**
In preparation to updating the lens distortion shaders to 3DE4R4 and LDPK v1.8.1. And before I do that, I have a question: why does the Obq Shaders' page says the UVRemap version is "deprecated" ?

See here: http://s3aws.obliquefx.com/public/shaders/help_files/Obq_UVRemapLensDistortion.html

I would rather use the UV distortion map shader than the camera shader. Is there a reason why I shouldn't?

Thanks.

### CODE REVIEW

**Comment by madesjardins** [comment]
Hey Vincent,

I think it was because SItoA stopped allowing the UVRemap  workflow,  no ?

So I created the Obq_LensDistortion shader instead.

--
Cheers
Marc-Antoine

**Comment by up4** [comment]
I didn't see it on the SiToA Camera support page: https://support.solidangle.com/display/SItoAUG/Camera+Maps

Do you remember where you saw that ? I work with the HtoA plugin and never read it either.

If it is indeed deprecated I'm going to use the camera shader but if it isn't I think it's easier to maintain a surface shader and use Arnold's standard perspective cam. No ?

**Comment by madesjardins** [comment]
Hey Vincent,

I've just download 1.8.1 and diffed it and there is no difference in the
headers, so nothing has changed except for the

// (C) 2011,2012,2013 - Science-D-Visions. Current version: 1.7

to

// (C) 2011,2012,2013,2014 - Science-D-Visions. Current version: 1.8.1

Which makes it quite easy to update : change the copyright lines only ;)


The stmap is now fed to a parameter of a property directly, you cannot
connect another shader to it and the arnold_uv_remap_persp_camera node does
not come with SItoA anymore. Here's a conversation I had with Steffano in
August 2014 :

****
Stefano:

Hi Marc-Antoine.
I'm afraid that's not possible anymore, and you'll have to code the custom
camera node (enabled back in 3.1.2).
Sorry for the inconvenience
- hide quoted text -


On Thu, Aug 21, 2014 at 2:35 PM, Marc-Antoine Desjardins <
madesj...@obliquefx.com> wrote:

> Hey list,
>
> Stefano, since arnold_uv_remap_persp_camera shader is gone in sitoa 3.1.2,
> how could I connect a node into the Perspective UV Remap of the camera
> options instead of an image ? This is how our (and at least a few others I
> think) distortion pipeline works, we use Obq_UVRemapLensDistortion
> connected to the image port of arnold_uv_remap_persp_camera, I don't want
> to use baked STMaps.
>
> Is it something that could be possible, I mean a node connected in a
> parameter of a property ? Otherwise, could you bring back the
> arnold_uv_remap_persp_camera ? If not, I'll just write a custom lens shader
> for it.
>
> Cheers
> --
> *Marc-Antoine Desjardins*
> Software Developer
> Oblique FX
> madesj...@obliquefx.co
> m
>

****

I don't mind updating the 2 that much because it is the exact same
modifications that have to be done. Actually, I should create a class and
both shaders call it instead of duplicating the code...

Cheers
-- 
Marc-Antoine Desjardins
514-806-6872

**Comment by up4** [comment]
Re **LDPK 1.8.1**: I think it's better to keep it to the latest version. But, your call.

Re **Arnold Camera UV Remap**: I will investigate further and if it works with HtoA I will keep it otherwise I will try your camera shader version.

**Pull request closed without merging**
